### ISSUE TITLE
I think you can approve the feedback of players when they win

### ISSUE THREAD

**Issue by fireairforce** [WanderHuang/react-minesweeper-sweep-it#1]
![saolei](https://user-images.githubusercontent.com/32598811/63075945-f4badd80-bf65-11e9-8ff4-cf169d08aa62.png)

As the picture,when i win the game,but i can't get any feedbacks of the game.

**Comment by WanderHuang** [comment]
Yeah, that would be added in sometime, I am thinking about this. Thank you for this issue. By the way, is this emoji in OS X?

**Comment by fireairforce** [comment]
thx,i think this project is cool,and my system is Ubuntu16.04

**Comment by WanderHuang** [comment]
Okay

**Comment by WanderHuang** [comment]
Game is updated.I use some simple animation to feed back to user when they get success or failure. Hope u like it.

**Comment by fireairforce** [comment]
it's cool!
